
package forms;

import beans.ApoioDatas;
import beans.Fornece;
import beans.Fornecedor;
import beans.Funcionario;
import beans.Produto;
import beans.Validade;
import estoqueDAO.ForneceDAO;
import estoqueDAO.FornecedorDAO;
import estoqueDAO.FuncionarioDAO;
import estoqueDAO.ProdutoDAO;
import estoqueDAO.ValidadeDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormCadastroProduto extends javax.swing.JFrame {

    private void limpaCampo() {
        txtCodBarra.setText("");
        txtNomeProduto.setText("");
        txtValorProduto.setText("");
        txtQuantidade.setValue(1);
        txtLote.setText("");
        txtValidade.setText("");
    }

    private void listarFuncionarios() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionario> listaFuncionario = funcionarioDAO.getListaFuncionarioCargo("Estoquista");
        cmbNomeFuncionario.removeAllItems();
        for (Funcionario f : listaFuncionario) {
            cmbNomeFuncionario.addItem(f.getNome_funcionario());
        }
    }

    private void listarFornecedor() {
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        List<Fornecedor> listaFornecedor = fornecedorDAO.ListaDeNomeFornecedor();
        cmbNomeFornecedor.removeAllItems();
        for (Fornecedor f : listaFornecedor) {
            cmbNomeFornecedor.addItem(f.getNomeFantasia());
        }
    }

    private void preencheCodigoFornecedorCmb() {
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        Fornecedor fornecedor = fornecedorDAO.getFornecedorPorNome(cmbNomeFornecedor.getSelectedItem().toString());
        txtCnpj.setText(fornecedor.getCnpj());
    }

    private void preencheCodigoFuncionarioCmb() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionarioPorNome(cmbNomeFuncionario.getSelectedItem().toString());
        txtCodFuncionario.setText(String.valueOf(funcionario.getId_funcionario()));
    }

    public FormCadastroProduto() {
        initComponents();
        listarFornecedor();
        preencheCodigoFornecedorCmb();
        listarFuncionarios();
        preencheCodigoFuncionarioCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        n = new javax.swing.JLabel();
        txtCodBarra = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        txtValorProduto = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JSpinner();
        txtLote = new javax.swing.JTextField();
        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        n5 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtValidade = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNomeFornecedor = new componentes.UJComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbNomeFuncionario = new componentes.UJComboBox();
        txtCodFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btnCodBarraPesquisa = new javax.swing.JButton();
        txtRelatorio = new javax.swing.JButton();
        txtCodBarraPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do produto"));

        n.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n.setText("Cod de Barras:");

        txtCodBarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBarraActionPerformed(evt);
            }
        });

        txtNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        txtValorProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProdutoActionPerformed(evt);
            }
        });

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txtLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });

        n1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n1.setText("Nome do Produto:");

        n2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n2.setText("Quantidade:");

        n3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n3.setText("Valor em R$:");

        n4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n4.setText("Lote:");

        n5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n5.setText("Validade:");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/add.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Edit.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        try {
            txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValidade.setMargin(new java.awt.Insets(3, 3, 3, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CNPJ do Fornecedor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Fornecedor:");

        cmbNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomeFornecedorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID do Funcionário:");

        cmbNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomeFuncionarioActionPerformed(evt);
            }
        });

        txtCodFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodFuncionarioFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome do Funcionário:");

        txtCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(n4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLote, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(n2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(n1)
                                    .addComponent(n))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(n3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(264, 264, 264)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(n5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n2)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLote, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(n4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n5)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel3);

        label1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label1.setText("Cod de Barras:");

        btnCodBarraPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCodBarraPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        btnCodBarraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodBarraPesquisaActionPerformed(evt);
            }
        });

        txtRelatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRelatorio.setText("Relatório dos Produtos Cadastrados");
        txtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelatorioActionPerformed(evt);
            }
        });

        txtCodBarraPesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodBarraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBarraPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRelatorio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodBarraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCodBarraPesquisa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCodBarraPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label1)
                        .addComponent(txtCodBarraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisa", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBarraActionPerformed

    }//GEN-LAST:event_txtCodBarraActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProdutoActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtCodBarra.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Códico de barra está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtNomeProduto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Nome do Produto está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtValorProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Valor do produto está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtLote.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lote está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtValidade.equals("##/##/####")) {
            JOptionPane.showMessageDialog(null, "Data está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else {

            String codBarra = txtCodBarra.getText();
            String nomeProduto = txtNomeProduto.getText();
            double valor = Double.parseDouble(txtValorProduto.getText());
            int quantidade = Integer.parseInt(txtQuantidade.getValue().toString());
            String lote = txtLote.getText();
            String data = txtValidade.getText();

            Funcionario funcionario = new Funcionario();
            funcionario.setId_funcionario(Integer.parseInt(txtCodFuncionario.getText()));

            Produto produto = new Produto();
            produto.setFk_id_funcionario(funcionario);
            produto.setCod_barra(codBarra);
            produto.setNome_produto(nomeProduto);
            produto.setValor_produto(valor);
            produto.setQuantidade_produto(quantidade);

            Validade validade = new Validade();
            validade.setfk_Cod_barra(produto);
            validade.setLote(lote);
            validade.setValidade(data);

            Fornecedor fornecedor = new Fornecedor();
            fornecedor.setCnpj(txtCnpj.getText());
            Fornece fornece = new Fornece();
            fornece.setFk_cod_barra(produto);
            fornece.setFk_cnpj(fornecedor);
            ApoioDatas pegaData = new ApoioDatas();
            try {
                fornece.setData_compra((pegaData.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())))
                );
            } catch (Exception ex) {
                Logger.getLogger(FormCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            ProdutoDAO produtoDAO = new ProdutoDAO();
            produtoDAO.inserirProduto(produto);
            ValidadeDAO validadeDAO = new ValidadeDAO();
            validadeDAO.inserirValidade(validade);
            ForneceDAO forneceDAO = new ForneceDAO();
            forneceDAO.inserirFornece(fornece);

            limpaCampo();


    }//GEN-LAST:event_btnSalvarActionPerformed

    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "Deseja editar Produto?")) {
            case 0:
                String codBarra = txtCodBarra.getText();
                String nomeProduto = txtNomeProduto.getText();
                double valor = Double.parseDouble(txtValorProduto.getText());
                int quantidade = Integer.parseInt(txtQuantidade.getValue().toString());
                String lote = txtLote.getText();
                String data = txtValidade.getText();
                ;

                Produto produto = new Produto();
                produto.setCod_barra(codBarra);
                produto.setNome_produto(nomeProduto);
                produto.setValor_produto(valor);
                produto.setQuantidade_produto(quantidade);
                Validade validade = new Validade();
                validade.setfk_Cod_barra(produto);
                validade.setLote(lote);
                validade.setValidade(data);

                ProdutoDAO produtoDAO = new ProdutoDAO();
                produtoDAO.editar(produto);
                ValidadeDAO validadeDAO = new ValidadeDAO();
                validadeDAO.editar(validade);

                JOptionPane.showMessageDialog(this, "Produto editado com sucesso!");
                limpaCampo();
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma alteração feita!");
                break;
            case 2:
                break;
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "Deseja excluir Produto?")) {
            case 0:
                String codBarra = txtCodBarra.getText();
                ProdutoDAO produtoDAO = new ProdutoDAO();
                produtoDAO.excluir(codBarra);
                ValidadeDAO validadeDAO = new ValidadeDAO();
                validadeDAO.excluir(codBarra);
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                limpaCampo();
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma alteração feita!");
                break;
            case 2:
                break;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    private void btnCodBarraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodBarraPesquisaActionPerformed
        String codPesquisa = txtCodBarraPesquisa.getText();
        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto produto = produtoDAO.getProduto(codPesquisa);
        ValidadeDAO validadeDAO = new ValidadeDAO();
        Validade validade = validadeDAO.getValidade(codPesquisa);

        if (produto == null) {
            JOptionPane.showMessageDialog(this, "Produto não encontrado!");
            limpaCampo();
        } else {
            JOptionPane.showMessageDialog(this, "Produto encontrado!");
            txtCodBarra.setText(codPesquisa);
            txtNomeProduto.setText(produto.getNome_produto());
            txtValorProduto.setText(String.valueOf(produto.getValor_produto()));
            txtQuantidade.setValue(produto.getQuantidade_produto());
            txtLote.setText(validade.getLote());
            txtValidade.setText(validade.getValidade());
        }
    }//GEN-LAST:event_btnCodBarraPesquisaActionPerformed

    private void txtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelatorioActionPerformed
        FormRelatorios fr = new FormRelatorios();
        fr.setVisible(true);
    }//GEN-LAST:event_txtRelatorioActionPerformed

    private void txtCodBarraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBarraPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBarraPesquisaActionPerformed

    private void cmbNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomeFornecedorActionPerformed
        // TODO add your handling code here:
        preencheCodigoFornecedorCmb();

    }//GEN-LAST:event_cmbNomeFornecedorActionPerformed

    private void txtCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFuncionarioFocusLost
        // TODO add your handling code here:
        int idPesquisa = Integer.parseInt(txtCodFuncionario.getText());
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionario(idPesquisa);
        cmbNomeFuncionario.setSelectedItem(funcionario.getNome_funcionario());
    }//GEN-LAST:event_txtCodFuncionarioFocusLost

    private void cmbNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomeFuncionarioActionPerformed
        // TODO add your handling code here:
        preencheCodigoFuncionarioCmb();
    }//GEN-LAST:event_cmbNomeFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCodBarraPesquisa;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private componentes.UJComboBox cmbNomeFornecedor;
    private componentes.UJComboBox cmbNomeFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtCodBarra;
    private javax.swing.JTextField txtCodBarraPesquisa;
    private javax.swing.JTextField txtCodFuncionario;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JButton txtRelatorio;
    private javax.swing.JFormattedTextField txtValidade;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
