
package forms;

import beans.Fornecedor;
import beans.Funcionario;
import estoqueDAO.FornecedorDAO;
import estoqueDAO.FuncionarioDAO;
import java.util.List;
import javax.swing.JOptionPane;

public class FormFornecedor extends javax.swing.JFrame {

    private void limpaCampo() {
        txtCnpj.setText("");
        txtNomeFantasia.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
    }

    private void listarFuncionarios() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionario> listaFuncionario = funcionarioDAO.getListaFuncionarioCargo("Estoquista");
        cmbNomeFuncionario.removeAllItems();
        for (Funcionario f : listaFuncionario) {
            cmbNomeFuncionario.addItem(f.getNome_funcionario());
        }
    }

    private void preencheCodigoFuncionarioCmb() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionarioPorNome(cmbNomeFuncionario.getSelectedItem().toString());
        txtCodFuncionario.setText(String.valueOf(funcionario.getId_funcionario()));
    }

    public FormFornecedor() {
        initComponents();
        listarFuncionarios();
        preencheCodigoFuncionarioCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Cadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tel1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        em1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pesquisar = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        txtCnpjPesquisa = new javax.swing.JFormattedTextField();
        btnCnpjPesquisa = new javax.swing.JButton();
        txtRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Fornecedor");

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/0001-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjActionPerformed(evt);
            }
        });

        txtNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantasiaActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label.setText("CNPJ:");

        n.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        n.setText("Nome Fantasia:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Funcionário:");

        txtCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodFuncionarioFocusLost(evt);
            }
        });

        jLabel7.setText("ID:");

        jLabel8.setText("Nome:");

        tel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tel1.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        em1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        em1.setText("email:");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/add.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Edit.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton1.setText("Limpar Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastrarLayout = new javax.swing.GroupLayout(Cadastrar);
        Cadastrar.setLayout(CadastrarLayout);
        CadastrarLayout.setHorizontalGroup(
            CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarLayout.createSequentialGroup()
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tel1)
                            .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(n)
                                .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(em1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFantasia)
                            .addGroup(CadastrarLayout.createSequentialGroup()
                                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CadastrarLayout.createSequentialGroup()
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(0, 9, Short.MAX_VALUE))))
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CadastrarLayout.setVerticalGroup(
            CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarLayout.createSequentialGroup()
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(1, 1, 1)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n)
                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarLayout.createSequentialGroup()
                                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(em1)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar)))
                .addGap(131, 131, 131))
        );

        jTabbedPane1.addTab("Cadastro", Cadastrar);

        Pesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Fornecedor"));

        label1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label1.setText("CNPJ do Fornecedor:");

        try {
            txtCnpjPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/0001-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjPesquisaActionPerformed(evt);
            }
        });

        btnCnpjPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCnpjPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        btnCnpjPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnpjPesquisaActionPerformed(evt);
            }
        });

        txtRelatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRelatorio.setText("Relatório dos Fornecedores Cadastrados");
        txtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PesquisarLayout = new javax.swing.GroupLayout(Pesquisar);
        Pesquisar.setLayout(PesquisarLayout);
        PesquisarLayout.setHorizontalGroup(
            PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRelatorio)
                    .addGroup(PesquisarLayout.createSequentialGroup()
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpjPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCnpjPesquisa)))
                .addGap(119, 119, 119))
        );
        PesquisarLayout.setVerticalGroup(
            PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label1)
                        .addComponent(txtCnpjPesquisa))
                    .addComponent(btnCnpjPesquisa))
                .addGap(18, 18, 18)
                .addComponent(txtRelatorio)
                .addGap(139, 139, 139))
        );

        jTabbedPane1.addTab("Pesquisa", Pesquisar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantasiaActionPerformed

    }//GEN-LAST:event_txtNomeFantasiaActionPerformed

    private void txtCnpjPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjPesquisaActionPerformed

    private void btnCnpjPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnpjPesquisaActionPerformed
        String cnpjPesquisa = txtCnpjPesquisa.getText();
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        Fornecedor fornecedor = fornecedorDAO.getFornecedorPorCnpj(cnpjPesquisa);
        if (fornecedor == null) {
            JOptionPane.showMessageDialog(this, "Fornecedor não encontrado!");
        } else {
            JOptionPane.showMessageDialog(this, "Fornecedor encontrado!");
            Pesquisar.setVisible(false);
            Cadastrar.setVisible(true);
            txtCodFuncionario.setText(String.valueOf(fornecedor.getFk_id_funcionario().getId_funcionario()));
            txtCnpj.setText(cnpjPesquisa);
            txtNomeFantasia.setText(fornecedor.getNomeFantasia());
            txtTelefone.setText(fornecedor.getTelefone());
            txtEmail.setText(fornecedor.getEmail());

        }
    }//GEN-LAST:event_btnCnpjPesquisaActionPerformed

    private void txtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelatorioActionPerformed
        FormRelatorios fr = new FormRelatorios();
        fr.setVisible(true);

    }//GEN-LAST:event_txtRelatorioActionPerformed

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjActionPerformed

    private void cmbNomeFuncionarioPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbNomeFuncionarioPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        preencheCodigoFuncionarioCmb();
    }//GEN-LAST:event_cmbNomeFuncionarioPopupMenuWillBecomeInvisible

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (txtCnpj.getText().equals("##.###.###/0001-##")) {
            JOptionPane.showMessageDialog(null, "Códico de barra está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtNomeFantasia.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Nome do Produto está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtTelefone.getText().equals("(##) #####-####")) {
            JOptionPane.showMessageDialog(null, "Valor do produto está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else if (txtEmail.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lote está vazio! seu preenchimento é Obrigatório", "Alerta!", JOptionPane.WARNING_MESSAGE);
        } else {

            String cnpj = txtCnpj.getText();
            String nomeFantasia = txtNomeFantasia.getText();
            String telefone = txtTelefone.getText();
            String email = txtEmail.getText();

            Funcionario funcionario = new Funcionario();
            funcionario.setId_funcionario(Integer.parseInt(txtCodFuncionario.getText()));

            Fornecedor fornecedor = new Fornecedor();
            fornecedor.setFk_id_funcionario(funcionario);
            fornecedor.setCnpj(cnpj);
            fornecedor.setNomeFantasia(nomeFantasia);
            fornecedor.setTelefone(telefone);
            fornecedor.setEmail(email);

            FornecedorDAO fornecedorDAO = new FornecedorDAO();
            fornecedorDAO.inserirFornecedor(fornecedor);

            limpaCampo();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(null, "Deseja editar Fornecedor?")) {
            case 0:
                String cnpj = txtCnpj.getText();
                String nomeFantasia = txtNomeFantasia.getText();
                String telefone = txtTelefone.getText();
                String email = txtEmail.getText();

                Funcionario funcionario = new Funcionario();
                funcionario.setId_funcionario(Integer.parseInt(txtCodFuncionario.getText()));

                Fornecedor fornecedor = new Fornecedor();
                fornecedor.setFk_id_funcionario(funcionario);
                fornecedor.setCnpj(cnpj);
                fornecedor.setNomeFantasia(nomeFantasia);
                fornecedor.setTelefone(telefone);
                fornecedor.setEmail(email);
                
                FornecedorDAO fornecedorDAO = new FornecedorDAO();
                fornecedorDAO.editar(fornecedor);
                limpaCampo();
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma alteração feita!");
                break;
            case 2:
                break;
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(null, "Deseja excluir Fornecedor?")) {
            case 0:
                String cnpj = txtCnpj.getText();
                FornecedorDAO fornecedorDAO = new FornecedorDAO();
                fornecedorDAO.excluir(cnpj);
                limpaCampo();
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma alteração feita!");
                break;
            case 2:
                break;
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFuncionarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFuncionarioFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpaCampo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastrar;
    private javax.swing.JPanel Pesquisar;
    private javax.swing.JButton btnCnpjPesquisa;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel em1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel tel1;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtCnpjPesquisa;
    private javax.swing.JTextField txtCodFuncionario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JButton txtRelatorio;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

}
