
package forms;

import beans.ApoioDatas;
import beans.Funcionario;
import beans.Produto;
import beans.Venda;
import beans.Vende_Produto;
import estoqueDAO.FuncionarioDAO;
import estoqueDAO.ProdutoDAO;
import estoqueDAO.VendaDAO;
import estoqueDAO.Vende_ProdutoDAO;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadastroVenda extends javax.swing.JFrame {

    double total_venda = 0;

    private void preencheVendasRealizadas() {

        VendaDAO vendaDAO = new VendaDAO();
        List<Venda> listaVenda = vendaDAO.getListaVenda();
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        NumberFormat moeda = NumberFormat.getCurrencyInstance(Locale.getDefault());

        DefaultTableModel tabelaVenda = (DefaultTableModel) tblPesquisaVenda.getModel();
        tabelaVenda.setNumRows(0);
        for (Venda v : listaVenda) {
            Object[] obj = new Object[]{
                v.getId_funcionario().getId_funcionario(),
                v.getId_funcionario().getNome_funcionario(),
                v.getId_venda(),
                moeda.format(v.getValor_total()),
                formatarDate.format(v.getData_venda())

            };
            tabelaVenda.addRow(obj);
        }
    }

    private void preencheCodigoFuncionarioCmb() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionarioPorNome(cmbNomeFuncionario.getSelectedItem().toString());
        txtCodFuncionario.setText(String.valueOf(funcionario.getId_funcionario()));
    }

    private void preencheCodigoProdutoCmb() {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto produto = produtoDAO.getProdutoPorNome(cmbNomeProduto.getSelectedItem().toString());
        txtCodProduto.setText(produto.getCod_barra());
    }

    private void listarFuncionarios() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionario> listaFuncionario = funcionarioDAO.getListaFuncionarioCargo("Operador de Caixa");
        cmbNomeFuncionario.removeAllItems();
        for (Funcionario f : listaFuncionario) {
            cmbNomeFuncionario.addItem(f.getNome_funcionario());
        }
    }

    private void preencherProduto() {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List<Produto> listaProduto = produtoDAO.getListaProduto("");
        cmbNomeProduto.removeAllItems();
        for (Produto p : listaProduto) {
            cmbNomeProduto.addItem(p.getNome_produto());
        }

    }

    private void preencheValorTotal() {
        NumberFormat moeda = NumberFormat.getCurrencyInstance(Locale.getDefault());

        double soma = 0, valor;
        int cont = tblVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) tblVendas.getValueAt(i, 4);
            soma += valor;
        }
        total_venda = soma;
        txtTotalVenda.setText(moeda.format(soma));

    }

    private void limparProdutoVenda() {
        txtTotalVenda.setText("");
        DefaultTableModel tabelaProduto = (DefaultTableModel) tblVendas.getModel();
        tabelaProduto.setNumRows(0);
    }

    public FormCadastroVenda() {
        initComponents();
        listarFuncionarios();
        preencherProduto();
        preencheCodigoFuncionarioCmb();
        preencheCodigoProdutoCmb();
        preencheVendasRealizadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodFuncionario = new javax.swing.JTextField();
        cmbNomeFuncionario = new componentes.UJComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        cmbNomeProduto = new componentes.UJComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnAdicionarVenda = new javax.swing.JButton();
        btnSalvarVenda = new javax.swing.JToggleButton();
        txtTotalVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnExcluirItem = new javax.swing.JButton();
        btnNovaVenda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        cmbCargo = new componentes.UJComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesquisaVenda = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Vendas");
        setResizable(false);

        jLabel1.setText("Código Fun.");

        txtCodFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodFuncionarioFocusLost(evt);
            }
        });
        txtCodFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodFuncionarioActionPerformed(evt);
            }
        });

        cmbNomeFuncionario.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbNomeFuncionarioPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Nome do Funcionário");

        jLabel3.setText("Cod. Produto");

        txtCodProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodProdutoFocusLost(evt);
            }
        });
        txtCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdutoActionPerformed(evt);
            }
        });

        cmbNomeProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbNomeProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomeProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        btnAdicionarVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/add-pequeno2.png"))); // NOI18N
        btnAdicionarVenda.setText("Adicionar");
        btnAdicionarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarVendaActionPerformed(evt);
            }
        });

        btnSalvarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/disk.png"))); // NOI18N
        btnSalvarVenda.setText("Salvar Venda");
        btnSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVendaActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor Total:");

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Barra", "Nome Produto", "Quant.", "Valor Unitario", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVendas);
        if (tblVendas.getColumnModel().getColumnCount() > 0) {
            tblVendas.getColumnModel().getColumn(0).setMinWidth(100);
            tblVendas.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblVendas.getColumnModel().getColumn(0).setMaxWidth(100);
            tblVendas.getColumnModel().getColumn(2).setMinWidth(70);
            tblVendas.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblVendas.getColumnModel().getColumn(2).setMaxWidth(70);
            tblVendas.getColumnModel().getColumn(3).setMinWidth(90);
            tblVendas.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblVendas.getColumnModel().getColumn(3).setMaxWidth(90);
            tblVendas.getColumnModel().getColumn(4).setMinWidth(90);
            tblVendas.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblVendas.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        btnExcluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete-pequeno.png"))); // NOI18N
        btnExcluirItem.setText("Excluir Item");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-vender-estoque-48-pequeno.png"))); // NOI18N
        btnNovaVenda.setText("Novo");
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome do Produto");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Cargo");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operador de Caixa" }));
        cmbCargo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodProduto)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cmbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdicionarVenda)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExcluirItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovaVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarVenda)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cmbNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarVenda)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirItem)
                    .addComponent(btnNovaVenda)
                    .addComponent(btnSalvarVenda)
                    .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        tblPesquisaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Funcionario", "Nome Funcionario", "Id venda", "Valor Total", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPesquisaVenda);
        if (tblPesquisaVenda.getColumnModel().getColumnCount() > 0) {
            tblPesquisaVenda.getColumnModel().getColumn(4).setMinWidth(90);
            tblPesquisaVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblPesquisaVenda.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jButton5.setText("Excluir Venda");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar vendas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório/Excluir", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFuncionarioActionPerformed

    private void btnAdicionarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarVendaActionPerformed

        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto listaProduto = produtoDAO.getProduto(txtCodProduto.getText());
        DefaultTableModel tabelaProduto = (DefaultTableModel) tblVendas.getModel();
        int quantidade = Integer.parseInt(txtQuantidade.getValue().toString());
        int cont = 0;

        for (int i = 0; i < cont; i++) {
            tabelaProduto.setNumRows(0);
        }
        tabelaProduto.addRow(new Object[]{
            listaProduto.getCod_barra(),
            listaProduto.getNome_produto(),
            txtQuantidade.getValue().toString(),
            listaProduto.getValor_produto(),
            quantidade * listaProduto.getValor_produto(),});
        preencheValorTotal();
        txtQuantidade.setValue(1);

    }//GEN-LAST:event_btnAdicionarVendaActionPerformed

    private void txtCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFuncionarioFocusLost
        // TODO add your handling code here:
        int idPesquisa = Integer.parseInt(txtCodFuncionario.getText());
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionario(idPesquisa);
        cmbNomeFuncionario.setSelectedItem(funcionario.getNome_funcionario());
    }//GEN-LAST:event_txtCodFuncionarioFocusLost
   
    private void txtCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodProdutoFocusLost
        // TODO add your handling code here:}}
        String codPesquisa = txtCodProduto.getText();
        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto produto = produtoDAO.getProduto(codPesquisa);
        cmbNomeProduto.setSelectedItem(produto.getNome_produto());

    }//GEN-LAST:event_txtCodProdutoFocusLost
    
    private void cmbNomeFuncionarioPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbNomeFuncionarioPopupMenuWillBecomeInvisible
        if (cmbNomeFuncionario.isPopupVisible()) {
            preencheCodigoFuncionarioCmb();
        }

    }//GEN-LAST:event_cmbNomeFuncionarioPopupMenuWillBecomeInvisible

    private void cmbNomeProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbNomeProdutoPopupMenuWillBecomeInvisible
        if (cmbNomeProduto.isPopupVisible()) {
            preencheCodigoProdutoCmb();
        }

    }//GEN-LAST:event_cmbNomeProdutoPopupMenuWillBecomeInvisible

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        limparProdutoVenda();
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void btnSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVendaActionPerformed
        Funcionario funcionario = new Funcionario();
        funcionario.setId_funcionario(Integer.parseInt(txtCodFuncionario.getText()));
        Venda venda = new Venda();
        venda.setId_funcionario(funcionario);
        venda.setValor_total(total_venda);
        ApoioDatas pegaData = new ApoioDatas();
        try {
            venda.setData_venda(pegaData.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis()))
            );
        } catch (Exception ex) {
            Logger.getLogger(FormCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        VendaDAO vendaDAO = new VendaDAO();
        vendaDAO.inserirVenda(venda);
        String cod_barra = null;
        int cont = tblVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            cod_barra = (String) tblVendas.getValueAt(i, 0);
        }
        
//        int id_venda = vendaDAO.getVenda();
//       
//        Produto produto = new Produto();
//        produto.setCod_barra(cod_barra);
//        Vende_Produto vende_produto = new Vende_Produto();
//        vende_produto.setFk_cod_barra(produto);
//        vende_produto.setFk_id_venda(id_venda);
//        Vende_ProdutoDAO vende_produtoDAO = new Vende_ProdutoDAO();
//        vende_produtoDAO.inserirVendeCod_Venda(vende_produto);
        limparProdutoVenda();

    }//GEN-LAST:event_btnSalvarVendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        preencheVendasRealizadas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);

        switch (JOptionPane.showConfirmDialog(null, "Deseja excluir Produto?")) {
            case 0:
                DefaultTableModel tabelaProduto = (DefaultTableModel) tblVendas.getModel();
                int linhaSelecionada = tblVendas.getSelectedRow();
                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(this, "Por favor, Selecione uma linha do produto pra excluir");
                } else {
                    tabelaProduto.removeRow(linhaSelecionada);
                    preencheValorTotal();
                    JOptionPane.showMessageDialog(this, "Produto Excluído!");
                }
                break;

            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma Exclusão feita!");
                break;
            case 2:
                break;
        }


    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);

        switch (JOptionPane.showConfirmDialog(null, "Deseja excluir a venda?")) {
            case 0:
                DefaultTableModel tabelaProduto = (DefaultTableModel) tblPesquisaVenda.getModel();
                int linhaSelecionada = tblPesquisaVenda.getSelectedRow();
                if (linhaSelecionada == -1) {
                    JOptionPane.showMessageDialog(this, "Por favor, Selecione uma linha da venda pra excluir");
                } else {
                    int id_venda = 0;
                    int cont = tblPesquisaVenda.getRowCount();
                    for (int i = 0; i < cont; i++) {
                        id_venda = (int) tblPesquisaVenda.getValueAt(i, 2);
                    }

                    VendaDAO vendaDAO = new VendaDAO();
                    vendaDAO.excluir(String.valueOf(id_venda));
                    preencheVendasRealizadas();
                    JOptionPane.showMessageDialog(this, "Venda Excluída!");
                }
                break;

            case 1:
                JOptionPane.showMessageDialog(this, "Nenhuma Exclusão feita!");
                break;
            case 2:
                break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdutoActionPerformed
    }//GEN-LAST:event_txtCodProdutoActionPerformed

    private void cmbNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomeProdutoActionPerformed
    }//GEN-LAST:event_cmbNomeProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarVenda;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JToggleButton btnSalvarVenda;
    private componentes.UJComboBox cmbCargo;
    private componentes.UJComboBox cmbNomeFuncionario;
    private componentes.UJComboBox cmbNomeProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPesquisaVenda;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtCodFuncionario;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JTextField txtTotalVenda;
    // End of variables declaration//GEN-END:variables
}
