
package forms;

import beans.Fornece;
import beans.Fornecedor;
import beans.Funcionario;
import beans.Produto;
import beans.Validade;
import estoqueDAO.ForneceDAO;
import estoqueDAO.FornecedorDAO;
import estoqueDAO.FuncionarioDAO;
import estoqueDAO.ProdutoDAO;
import estoqueDAO.ValidadeDAO;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;


public class FormRelatorios extends javax.swing.JFrame {

    private void preencheTabelaFornecedor() {

        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        String fornecedorPesquisa = txtPesquisaFornecedor.getText();
        List<Fornecedor> listaFornecedor = fornecedorDAO.getListaForcenedor(fornecedorPesquisa);

        DefaultTableModel tabelaFornecedores = (DefaultTableModel) tblFornecedores.getModel();
        tabelaFornecedores.setNumRows(0);
        for (Fornecedor f : listaFornecedor) {
            Object[] obj = new Object[]{
                f.getCnpj(),
                f.getNomeFantasia(),
                f.getTelefone(),
                f.getEmail()
            };
            tabelaFornecedores.addRow(obj);
        }
    }
    
    private void preencheTabelaFuncionario() {

        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        String funcionarioPesquisa = txtPesquisaFornecedor.getText();
        List<Funcionario> listaFuncionario = funcionarioDAO.getListaFuncionario(funcionarioPesquisa);

        DefaultTableModel tabelaFuncionario = (DefaultTableModel) tblFuncionarios.getModel();
        tabelaFuncionario.setNumRows(0);
        for (Funcionario f : listaFuncionario) {
            Object[] obj = new Object[]{
                f.getId_funcionario(),
                f.getNome_funcionario(),
                f.getCargo()
            };
            tabelaFuncionario.addRow(obj);
        }
    }

    private void preencheTabelaFornece() {

        ForneceDAO forneceDAO = new ForneceDAO();
        
        List<Fornece> listaFornece = forneceDAO.getListaForneceProduto();

        DefaultTableModel tabelaFornece = (DefaultTableModel) tblFornece.getModel();
        tabelaFornece.setNumRows(0);
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        for (Fornece f : listaFornece) {
            Object[] obj = new Object[]{
                f.getFk_cod_barra().getCod_barra(),
                f.getFk_cod_barra().getNome_produto(),
                f.getFk_cnpj().getNomeFantasia(),
                formatarDate.format(f.getData_compra())
            };
            tabelaFornece.addRow(obj);
        }
    }

    private void preencheTabelaProduto() {

        ValidadeDAO validadeDAO = new ValidadeDAO();
        List<Validade> listaValidade = validadeDAO.getListaValidade();

        DefaultTableModel tabelaProduto = (DefaultTableModel) tblProdutos.getModel();
        NumberFormat moeda = NumberFormat.getCurrencyInstance(Locale.getDefault());
        tabelaProduto.setNumRows(0);
        for(Validade v : listaValidade){
            Object[] obj = new Object[]{
                v.getfk_Cod_barra().getCod_barra(),
                v.getfk_Cod_barra().getNome_produto(),
                moeda.format(v.getfk_Cod_barra().getValor_produto()),
                v.getfk_Cod_barra().getQuantidade_produto(),
                v.getLote(),
                v.getValidade()
            };
            tabelaProduto.addRow(obj);
        }
    }

    public FormRelatorios() {
        initComponents();
        preencheTabelaFornecedor();
        preencheTabelaFuncionario();
        preencheTabelaProduto();
        preencheTabelaFornece();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        RELATORIO_FORNECEDOR = new javax.swing.JPanel();
        RELATORIO_FORNECEDOR_ = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisaFornecedor = new javax.swing.JTextField();
        RELATORIO_FUNCIONARIO = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisaFuncionario = new javax.swing.JTextField();
        RELATORIO_PRODUTO = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFornece = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios do SoftGES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("RELATÓRIO DE FORNECEDORES");

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "NOME FANTASIA", "TELEFONE", "E-MAIL"
            }
        ));
        jScrollPane1.setViewportView(tblFornecedores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PESQUISA POR NOME");

        txtPesquisaFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisaFornecedor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaFornecedorCaretUpdate(evt);
            }
        });
        txtPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RELATORIO_FORNECEDOR_Layout = new javax.swing.GroupLayout(RELATORIO_FORNECEDOR_);
        RELATORIO_FORNECEDOR_.setLayout(RELATORIO_FORNECEDOR_Layout);
        RELATORIO_FORNECEDOR_Layout.setHorizontalGroup(
            RELATORIO_FORNECEDOR_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(RELATORIO_FORNECEDOR_Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RELATORIO_FORNECEDOR_Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158))
        );
        RELATORIO_FORNECEDOR_Layout.setVerticalGroup(
            RELATORIO_FORNECEDOR_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RELATORIO_FORNECEDOR_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RELATORIO_FORNECEDOR_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout RELATORIO_FORNECEDORLayout = new javax.swing.GroupLayout(RELATORIO_FORNECEDOR);
        RELATORIO_FORNECEDOR.setLayout(RELATORIO_FORNECEDORLayout);
        RELATORIO_FORNECEDORLayout.setHorizontalGroup(
            RELATORIO_FORNECEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RELATORIO_FORNECEDOR_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RELATORIO_FORNECEDORLayout.setVerticalGroup(
            RELATORIO_FORNECEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RELATORIO_FORNECEDOR_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FORNECEDORES", RELATORIO_FORNECEDOR);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("RELATÓRIO DE FUNCIONÁRIOS");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CARGO"
            }
        ));
        jScrollPane2.setViewportView(tblFuncionarios);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PESQUISA POR NOME");

        txtPesquisaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisaFuncionario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaFuncionarioCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(162, 162, 162))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout RELATORIO_FUNCIONARIOLayout = new javax.swing.GroupLayout(RELATORIO_FUNCIONARIO);
        RELATORIO_FUNCIONARIO.setLayout(RELATORIO_FUNCIONARIOLayout);
        RELATORIO_FUNCIONARIOLayout.setHorizontalGroup(
            RELATORIO_FUNCIONARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RELATORIO_FUNCIONARIOLayout.setVerticalGroup(
            RELATORIO_FUNCIONARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FUNCIONÁRIOS", RELATORIO_FUNCIONARIO);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("RELATÓRIO DE PRODUTOS");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO DE BARRAS", "NOME DO PRODUTO", "VALOR", "QUANTIDADE", "LOTE", "VALIDADE"
            }
        ));
        jScrollPane3.setViewportView(tblProdutos);

        javax.swing.GroupLayout RELATORIO_PRODUTOLayout = new javax.swing.GroupLayout(RELATORIO_PRODUTO);
        RELATORIO_PRODUTO.setLayout(RELATORIO_PRODUTOLayout);
        RELATORIO_PRODUTOLayout.setHorizontalGroup(
            RELATORIO_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(RELATORIO_PRODUTOLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RELATORIO_PRODUTOLayout.setVerticalGroup(
            RELATORIO_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RELATORIO_PRODUTOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PRODUTOS", RELATORIO_PRODUTO);

        tblFornece.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD BARRA", "NOME DO PROTUDO", "FORNECEDOR", "DATA DA COMPRA"
            }
        ));
        jScrollPane4.setViewportView(tblFornece);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Fornecedor/Produto/Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Fornecedor/Produto", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("RELATORIO DO SOFTGES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaFornecedorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaFornecedorCaretUpdate
        // TODO add your handling code here:
        preencheTabelaFornecedor();
    }//GEN-LAST:event_txtPesquisaFornecedorCaretUpdate

    private void txtPesquisaFuncionarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaFuncionarioCaretUpdate
        // TODO add your handling code here:
        preencheTabelaFuncionario();
    }//GEN-LAST:event_txtPesquisaFuncionarioCaretUpdate

    private void txtPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RELATORIO_FORNECEDOR;
    private javax.swing.JPanel RELATORIO_FORNECEDOR_;
    private javax.swing.JPanel RELATORIO_FUNCIONARIO;
    private javax.swing.JPanel RELATORIO_PRODUTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblFornece;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtPesquisaFornecedor;
    private javax.swing.JTextField txtPesquisaFuncionario;
    // End of variables declaration//GEN-END:variables
}
